name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest
    outputs:
      skip: ${{ steps.check_skip.outputs.skip }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Check for #skip in commit
        id: check_skip
        run: echo "skip=${{ contains(github.event.head_commit.message || github.event.pull_request.body, '#skip') }}" >> $GITHUB_OUTPUT
      
      - name: Check for #fail in commit
        id: check_fail
        run: echo "fail=${{ contains(github.event.head_commit.message || github.event.pull_request.body, '#fail') }}" >> $GITHUB_OUTPUT
      
      - name: Make build fail on purpose
        if: ${{ steps.check_fail.outputs.fail == 'true' }}
        run: |
          echo "Forcing failure"
          exit 1

      - name: install dependencies
        run: npm install
        
      - name: Check style
        run: npm run eslint

      - name: Build 
        run: npm run build

      - name: Test
        run: npm run test
          
      - name: Trigger deployment
        if: ${{ github.event_name == 'push' && steps.check_skip.outputs.skip == 'false' }}
        run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}
      
      - name: Debug webhook presence
        if: failure()
        run: |
          echo "Webhook length: ${#DISCORD_WEBHOOK}"
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}

      - name: Build Failed
        uses: rjstone/discord-webhook-notify@v2
        if: failure()
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          username: GitHub
          avatarUrl: https://github.com/fluidicon.png
          text: "Build failed!"
          severity: error
          color: '#f20303ff'

  tag_release:
    needs: [simple_deployment_pipeline]
    if: ${{ github.event_name == 'push' && needs.simple_deployment_pipeline.outputs.skip == 'false' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.75.0
        env:
          DEFAULT_BUMP: patch
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: New version deployed!
        uses: rjstone/discord-webhook-notify@v2
        if: success()
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          username: GitHub
          avatarUrl: https://github.com/fluidicon.png
          text: "New version deployed!"
          severity: info
          color: '#1ff203ff'